name: frontend-ci
on: [push]
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - run: echo '[Container] Phase complete: BUILD SUCCESS' > frontend.log
   - run: aws s3 cp frontend.log s3://mp4-logs-635114519658/frontend-logs/frontend-log.gz
     env:
       AWS_DEFAULT_REGION: us-east-1
